wrk.method = "GET"
wrk.headers["oneflow-user"] = "ajohnston"
wrk.headers["oneflow-timestamp"] = "foo"
wrk.headers["oneflow-authorization"] = "xT3cWOtlUuIW1/YeVc2OjKMe+y0="
wrk.headers["bearer-token"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsInVzZXJuYW1lIjoiYWpvaG5zdG9uIn0.FTvkCZF1hstwwzu3_G7VImdlSS1_v4jZZ08RvuCNUNI"